spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/tmallsql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.it.bean
  mapper-locations: classpath:mappers/*.xml

# 打印MyBatis的SQL语句
logging:
  level:
    com.it.mapper: debug