server:
  port: 7003 # 端口

spring:
  application:
    name: eureka7003.com # 应用名称，会在Eureka中显示

eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka